# Generated by the UIRibbon build, do NOT modify

CmdAppMenu = 2
CmdQAT = 3
CmdTab1 = 4
CmdTab1_LabelTitle_RESID = 60001
CmdTab1Group1 = 5
CmdTab1Group1_LabelTitle_RESID = 60002
CmdTab1Group1_LabelDescription_RESID = 60003
CmdTab1Group1_TooltipDescription_RESID = 60004
CmdSpinner1 = 6
CmdSpinner1_LabelTitle_RESID = 60005
CmdSpinner1_LabelDescription_RESID = 60006
CmdSpinner1_TooltipDescription_RESID = 60007
