# Generated by the UIRibbon build, do NOT modify

CmdAppMenu = 2
CmdQAT = 3
CmdTab1 = 4
CmdTab1_LabelTitle_RESID = 60001
CmdTab1Group1 = 5
CmdTab1Group1_LabelTitle_RESID = 60002
CmdTab1Group1_LabelDescription_RESID = 60003
CmdTab1Group1_TooltipDescription_RESID = 60004
CmdTab1Group1_SmallImages_RESID = 60005
CmdTab1Group1_SmallImages_120__RESID = 60006
CmdTab1Group1_LargeImages_RESID = 60007
CmdTab1Group1_LargeImages_120__RESID = 60008
CmdButton1 = 6
CmdButton1_LabelTitle_RESID = 60009
CmdButton1_LabelDescription_RESID = 60010
CmdButton1_TooltipDescription_RESID = 60011
CmdButton1_SmallImages_RESID = 60012
CmdButton1_SmallImages_120__RESID = 60013
CmdButton1_LargeImages_RESID = 60014
CmdButton1_LargeImages_120__RESID = 60015
CmdContextMap1 = 7
