# Generated by the UIRibbon build, do NOT modify

CmdAppMenu = 2
CmdQAT = 3
CmdTab1 = 4
CmdTab1_LabelTitle_RESID = 60001
CmdTabGroup1 = 5
CmdTabGroup1_LabelTitle_RESID = 60002
CmdTabGroup1Tab1 = 6
CmdTabGroup1Tab1_LabelTitle_RESID = 60003
CmdTabGroup1Tab2 = 7
CmdTabGroup1Tab2_LabelTitle_RESID = 60004
