require_relative 'comctl/Button'
require_relative 'comctl/SysLink' if Fzeet::Windows::Version >= :xp
require_relative 'comctl/Edit'
require_relative 'comctl/UpDown'
require_relative 'comctl/MonthCalendar'
require_relative 'comctl/DateTimePicker'
require_relative 'comctl/ComboBox'
require_relative 'comctl/ComboBoxEx'
require_relative 'comctl/Header'
require_relative 'comctl/ListView'
require_relative 'comctl/TreeView'
require_relative 'comctl/ProgressBar'
require_relative 'comctl/PropertySheet'
require_relative 'comctl/Tab'
